### ISSUE TITLE
SciChart.js does not work with Create React App. Uncaught (in promise) TypeError: WasmModule2D is not a constructor

### ISSUE THREAD

**Issue by puremood2002** [ABTSoftware/SciChart.JS.Examples#10]
Hi 

I created a minimal react app with scichart.js, with a single component, it throws this error at run time
Uncaught (in promise) TypeError: WasmModule2D is not a constructor
Attached is the react app with this problem, please advise, thanks a lot.

[hello-issue-demo.zip](https://github.com/ABTSoftware/SciChart.JS.Examples/files/5441229/hello-issue-demo.zip)

**Comment by klishevich** [comment]
@puremood2002  thank you for the issue and zip file. The problem is that Create React App does not support WebAssembly (https://stackoverflow.com/questions/59319775/how-to-use-webassembly-wasm-with-create-react-app) as for now I created a template project React + SciChart (https://github.com/klishevich/react-scichart-demo) and we will look into how to use Create React App with SciChart

**Comment by puremood2002** [comment]
Thanks

**Comment by klishevich** [comment]
We created Create React App Demo with SciChart.js - https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/demo-create-react-app-scichart
